<#--
    THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS
    FOR A PARTICULAR PURPOSE. THIS CODE AND INFORMATION ARE NOT SUPPORTED BY XEBIALABS.
-->
#!/bin/sh

pushd ${previousDeployed.targetDirectory} || exit 1

MANIFEST=".xldeploy-manifest-${previousDeployed.deployable.name}"
rm -rv $(cat "$MANIFEST")
rm "$MANIFEST"
